# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lambdago2

custom:
  stage: ${self:provider.stage}
  eventsTableName: ${self:service}-${self:provider.stage}-events
  eventsTableArn:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - dynamodb
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - table/${self:custom.eventsTableName}

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: ap-south-1
  environment:
    EVENTS_TABLE_NAME: ${self:custom.eventsTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynaomdb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.eventsTableArn}


resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}

package:
 individually: true
 exclude:
   - ./**

functions:
  deleteEvent:
    handler: bin/handlers/deleteEvent
    package:
      include:
        - ./bin/handlers/deleteEvent
    events:
      - http:
          path: events/{event_id}
          method: delete
          cors: true
          authorizer: aws_iam
  completeEvent:
    handler: bin/handlers/completeEvent
    package:
      include:
        - ./bin/handlers/completeEvent
    events:
      - http:
          path: events/{event_id}
          method: patch
          cors: true
          authorizer: aws_iam
  listEvents:
    handler: bin/handlers/listEvents
    package:
      include:
        - ./bin/handlers/listEvents
    events:
      - http:
          path: events
          method: get
          cors: true
          authorizer: aws_iam
  addEvent:
    handler: bin/handlers/addEvent
    package:
     include:
       - ./bin/handlers/addEvent
    events:
      - http:
          path: events
          method: post
          cors: true
          authorizer: aws_iam
